image: kylef/swiftenv

before_script:
  - swiftenv install 4.2

cache:
  key: "$CI_BUILD_REF_NAME-$CI_COMMIT_REF_NAME"
  paths:
    - .build

test:
  script:
    - swift package resolve
    - swift package clean
    - swift test
  tags:
    - swift