image: swift:4.2

stages:
  - test
  - deploy

cache:
  key: "$CI_BUILD_REF_NAME-$CI_COMMIT_REF_NAME"
  paths:
    - .build

services:
  - postgres

variables:
  DATABASE_URL: postgresql://jimmy:password@postgres:5432/microservice 
  ACCESS_TOKEN_VALID_DURATION: 3600 
  JWT_SECRET: test 
  REFRESH_TOKEN_VALID_DURATION: 2592000
  USERS_HOST: http://user-service:8080
  POSTGRES_DB: microservice
  POSTGRES_USER: jimmy
  POSTGRES_PASSWORD: password

test:
  stage: test
  script:
    - swift package resolve
    - swift package clean
    - swift test
  tags:
    - docker

deploy-master:
  stage: deploy
  when: on_success
  only:
   - master
  script:
    - export
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/jimmya92/vapor-microservice-idp:latest .
    - docker push registry.gitlab.com/jimmya92/vapor-microservice-idp:latest
  tags:
    - ssh

deploy-tag:
  stage: deploy
  when: on_success
  only:
   - tags
  script:
    - export
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/jimmya92/vapor-microservice-idp:$CI_COMMIT_REF_NAME .
    - docker push registry.gitlab.com/jimmya92/vapor-microservice-idp:$CI_COMMIT_REF_NAME
  tags:
    - ssh
